<MainLayout>
    MDBoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        MDToolbar:
            title: "Youtube Downloader App"

        MDBoxLayout:
            orientation: "vertical"
            size: root.width, root.height
            spacing: 8
            padding: 8

            MDProgressBar:
                id: progress_bar
                type: "indeterminate"

            AsyncImage:
                id: thumbnail
                source: ''
                size: root.width, 300

            MDLabel:
                id: title_video
                halign: "center"

            MDTextField:
                id: txt_input_url
                hint_text: "Input Link Youtube"

            MDFillRoundFlatButton:
                text: "Cari"
                pos_hint: {"top":0.7}
                on_press: root.cari(txt_input_url.text)

            MDRectangleFlatButton:
                text: "Download Video"
                size_hint: [1, .3]
                on_press: root.download_video()

            MDRectangleFlatButton:
                text: "Download Subtitle"
                size_hint: [1, .3]
                on_press: root.download_subtitle()
